import type { Province } from "@/lib/models/location";

export const PHILIPPINES_LOCATIONS: Province[] = [
  {
    name: "Metro Manila",
    cities: [
      { name: "Manila" },
      { name: "Makati" },
      { name: "Quezon City" },
      { name: "Pasig" },
      { name: "Caloocan" },
      { name: "Las Piñas" },
      { name: "Parañaque" },
      { name: "San Juan" },
      { name: "Mandaluyong" },
      { name: "Marikina" },
      { name: "Pasay" },
      { name: "Taguig" },
      { name: "Muntinlupa" },
      { name: "Navotas" },
      { name: "Malabon" },
      { name: "Valenzuela" },
    ],
  },
   {
       "name": "Abra",
      "cities": [
        { "name": "Bangued", "isCapital": true },
        { "name": "Boliney" },
        { "name": "Bucay" },
        { "name": "Bucloc" },
        { "name": "Daguioman" },
        { "name": "Danglas" },
        { "name": "Dolores" },
        { "name": "La Paz" },
        { "name": "Lacub" },
        { "name": "Lagangilang" },
        { "name": "Lagayan" },
        { "name": "Langiden" },
        { "name": "Licuan-Baay" },
        { "name": "Luba" },
        { "name": "Malibcong" },
        { "name": "Manabo" },
        { "name": "Peñarrubia" },
        { "name": "Pidigan" },
        { "name": "Pilar" },
        { "name": "Sallapadan" },
        { "name": "San Isidro" },
        { "name": "San Juan" },
        { "name": "San Quintin" },
        { "name": "Tayum" },
        { "name": "Tineg" },
        { "name": "Tubo" },
        { "name": "Villaviciosa" }
      ]
    },
    {
      "name": "Agusan del Norte",
      "cities": [
        { "name": "Cabadbaran City", "isCapital": true },
        { "name": "Butuan City" },
        { "name": "Buenavista" },
        { "name": "Carmen" },
        { "name": "Jabonga" },
        { "name": "Kitcharao" },
        { "name": "Las Nieves" },
        { "name": "Magallanes" },
        { "name": "Nasipit" },
        { "name": "Remedios T. Romualdez" },
        { "name": "Santiago" },
        { "name": "Tubay" }
      ]
    },
    {
      "name": "Agusan del Sur",
      "cities": [
        { "name": "Prosperidad", "isCapital": true },
        { "name": "Bayugan City" },
        { "name": "Bunawan" },
        { "name": "Esperanza" },
        { "name": "La Paz" },
        { "name": "Loreto" },
        { "name": "Rosario" },
        { "name": "San Francisco" },
        { "name": "San Luis" },
        { "name": "Santa Josefa" },
        { "name": "Sibagat" },
        { "name": "Talacogon" },
        { "name": "Trento" },
        { "name": "Veruela" }
      ]
    },
    {
      "name": "Aklan",
      "cities": [
        { "name": "Kalibo", "isCapital": true },
        { "name": "Altavas" },
        { "name": "Balete" },
        { "name": "Banga" },
        { "name": "Batan" },
        { "name": "Buruanga" },
        { "name": "Ibajay" },
        { "name": "Lezo" },
        { "name": "Libacao" },
        { "name": "Madalag" },
        { "name": "Makato" },
        { "name": "Malay" },
        { "name": "Malinao" },
        { "name": "Nabas" },
        { "name": "New Washington" },
        { "name": "Numancia" },
        { "name": "Tangalan" }
      ]
    },
    {
      "name": "Albay",
      "cities": [
        { "name": "Legazpi City", "isCapital": true },
        { "name": "Ligao City" },
        { "name": "Tabaco City" },
        { "name": "Bacacay" },
        { "name": "Camalig" },
        { "name": "Daraga" },
        { "name": "Guinobatan" },
        { "name": "Jovellar" },
        { "name": "Libon" },
        { "name": "Malilipot" },
        { "name": "Malinao" },
        { "name": "Manito" },
        { "name": "Oas" },
        { "name": "Pio Duran" },
        { "name": "Polangui" },
        { "name": "Rapu-Rapu" },
        { "name": "Santo Domingo" },
        { "name": "Tiwi" }
      ]
    },
    {
      "name": "Antique",
      "cities": [
        { "name": "San Jose de Buenavista", "isCapital": true },
        { "name": "Anini-y" },
        { "name": "Barbaza" },
        { "name": "Belison" },
        { "name": "Bugasong" },
        { "name": "Caluya" },
        { "name": "Culasi" },
        { "name": "Tobias Fornier" },
        { "name": "Hamtic" },
        { "name": "Laua-an" },
        { "name": "Libertad" },
        { "name": "Pandan" },
        { "name": "Patnongon" },
        { "name": "San Remigio" },
        { "name": "Sebaste" },
        { "name": "Sibalom" },
        { "name": "Tibiao" },
        { "name": "Valderrama" }
      ]
    },
    {
      "name": "Apayao",
      "cities": [
        { "name": "Kabugao", "isCapital": true },
        { "name": "Calanasan" },
        { "name": "Conner" },
        { "name": "Flora" },
        { "name": "Luna" },
        { "name": "Pudtol" },
        { "name": "Santa Marcela" }
      ]
    },
    {
      "name": "Aurora",
      "cities": [
        { "name": "Baler", "isCapital": true },
        { "name": "Casiguran" },
        { "name": "Dilasag" },
        { "name": "Dinalungan" },
        { "name": "Dingalan" },
        { "name": "Dipaculao" },
        { "name": "Maria Aurora" },
        { "name": "San Luis" }
      ]
    },
    {
      "name": "Basilan",
      "cities": [
        { "name": "Isabela City", "isCapital": true },
        { "name": "Lamitan City" },
        { "name": "Akbar" },
        { "name": "Al-Barka" },
        { "name": "Hadji Mohammad Ajul" },
        { "name": "Hadji Muhtamad" },
        { "name": "Lantawan" },
        { "name": "Maluso" },
        { "name": "Sumisip" },
        { "name": "Tabuan-Lasa" },
        { "name": "Tipo-Tipo" },
        { "name": "Tuburan" },
        { "name": "Ungkaya Pukan" }
      ]
    },
    {
      "name": "Bataan",
      "cities": [
        { "name": "Balanga City", "isCapital": true },
        { "name": "Abucay" },
        { "name": "Bagac" },
        { "name": "Dinalupihan" },
        { "name": "Hermosa" },
        { "name": "Limay" },
        { "name": "Mariveles" },
        { "name": "Morong" },
        { "name": "Orani" },
        { "name": "Orion" },
        { "name": "Pilar" },
        { "name": "Samal" }
      ]
    },
    {
      "name": "Batanes",
      "cities": [
        { "name": "Basco", "isCapital": true },
        { "name": "Itbayat" },
        { "name": "Ivana" },
        { "name": "Mahatao" },
        { "name": "Sabtang" },
        { "name": "Uyugan" }
      ]
    },
    {
      "name": "Batangas",
      "cities": [
        { "name": "Batangas City", "isCapital": true },
        { "name": "Lipa City" },
        { "name": "Tanauan City" },
        { "name": "Agoncillo" },
        { "name": "Alitagtag" },
        { "name": "Balayan" },
        { "name": "Balete" },
        { "name": "Bauan" },
        { "name": "Calaca" },
        { "name": "Calatagan" },
        { "name": "Cuenca" },
        { "name": "Ibaan" },
        { "name": "Laurel" },
        { "name": "Lemery" },
        { "name": "Lian" },
        { "name": "Lobo" },
        { "name": "Mabini" },
        { "name": "Malvar" },
        { "name": "Mataasnakahoy" },
        { "name": "Nasugbu" },
        { "name": "Padre Garcia" },
        { "name": "Rosario" },
        { "name": "San Jose" },
        { "name": "San Juan" },
        { "name": "San Luis" },
        { "name": "San Nicolas" },
        { "name": "San Pascual" },
        { "name": "Santa Teresita" },
        { "name": "Santo Tomas" },
        { "name": "Taal" },
        { "name": "Talisay" },
        { "name": "Taysan" },
        { "name": "Tingloy" },
        { "name": "Tuy" }
      ]
    },
    {
      "name": "Benguet",
      "cities": [
        { "name": "La Trinidad", "isCapital": true },
        { "name": "Baguio City" },
        { "name": "Atok" },
        { "name": "Bakun" },
        { "name": "Bokod" },
        { "name": "Buguias" },
        { "name": "Itogon" },
        { "name": "Kabayan" },
        { "name": "Kapangan" },
        { "name": "Kibungan" },
        { "name": "Mankayan" },
        { "name": "Sablan" },
        { "name": "Tuba" },
        { "name": "Tublay" }
      ]
    },
    {
      "name": "Biliran",
      "cities": [
        { "name": "Naval", "isCapital": true },
        { "name": "Almeria" },
        { "name": "Biliran" },
        { "name": "Cabucgayan" },
        { "name": "Caibiran" },
        { "name": "Culaba" },
        { "name": "Kawayan" },
        { "name": "Maripipi" }
      ]
    },
    {
      "name": "Bohol",
      "cities": [
        { "name": "Tagbilaran City", "isCapital": true },
        { "name": "Albuquerque" },
        { "name": "Alicia" },
        { "name": "Anda" },
        { "name": "Antequera" },
        { "name": "Baclayon" },
        { "name": "Balilihan" },
        { "name": "Batuan" },
        { "name": "Bien Unido" },
        { "name": "Bilar" },
        { "name": "Buenavista" },
        { "name": "Calape" },
        { "name": "Candijay" },
        { "name": "Carmen" },
        { "name": "Catigbian" },
        { "name": "Clarin" },
        { "name": "Corella" },
        { "name": "Cortes" },
        { "name": "Dagohoy" },
        { "name": "Danao" },
        { "name": "Dauis" },
        { "name": "Dimiao" },
        { "name": "Duero" },
        { "name": "Garcia Hernandez" },
        { "name": "Getafe" },
        { "name": "Guindulman" },
        { "name": "Inabanga" },
        { "name": "Jagna" },
        { "name": "Lila" },
        { "name": "Loay" },
        { "name": "Loboc" },
        { "name": "Loon" },
        { "name": "Mabini" },
        { "name": "Maribojoc" },
        { "name": "Panglao" },
        { "name": "Pilar" },
        { "name": "President Carlos P. Garcia" },
        { "name": "Sagbayan" },
        { "name": "San Isidro" },
        { "name": "San Miguel" },
        { "name": "Sevilla" },
        { "name": "Sierra Bullones" },
        { "name": "Sikatuna" },
        { "name": "Talibon" },
        { "name": "Trinidad" },
        { "name": "Tubigon" },
        { "name": "Ubay" },
        { "name": "Valencia" }
      ]
    },
    {
      "name": "Bukidnon",
      "cities": [
        { "name": "Malaybalay City", "isCapital": true },
        { "name": "Valencia City" },
        { "name": "Baungon" },
        { "name": "Cabanglasan" },
        { "name": "Damulog" },
        { "name": "Dangcagan" },
        { "name": "Don Carlos" },
        { "name": "Impasugong" },
        { "name": "Kadingilan" },
        { "name": "Kalilangan" },
        { "name": "Kibawe" },
        { "name": "Kitatao" },
        { "name": "Lantapan" },
        { "name": "Libona" },
        { "name": "Malitbog" },
        { "name": "Manolo Fortich" },
        { "name": "Maramag" },
        { "name": "Pangantucan" },
        { "name": "Quezon" },
        { "name": "San Fernando" },
        { "name": "Sumilao" },
        { "name": "Talakag" }
      ]
    },
    {
      "name": "Bulacan",
      "cities": [
        { "name": "Malolos City", "isCapital": true },
        { "name": "Meycauayan City" },
        { "name": "San Jose del Monte City" },
        { "name": "Angat" },
        { "name": "Balagtas" },
        { "name": "Baliuag" },
        { "name": "Bocaue" },
        { "name": "Bulakan" },
        { "name": "Bustos" },
        { "name": "Calumpit" },
        { "name": "Doña Remedios Trinidad" },
        { "name": "Guiguinto" },
        { "name": "Hagonoy" },
        { "name": "Marilao" },
        { "name": "Norzagaray" },
        { "name": "Obando" },
        { "name": "Pandi" },
        { "name": "Paombong" },
        { "name": "Plaridel" },
        { "name": "Pulilan" },
        { "name": "San Ildefonso" },
        { "name": "San Miguel" },
        { "name": "San Rafael" },
        { "name": "Santa Maria" }
      ]
    },
    {
      "name": "Cagayan",
      "cities": [
        { "name": "Tuguegarao City", "isCapital": true },
        { "name": "Abulug" },
        { "name": "Alcala" },
        { "name": "Allacapan" },
        { "name": "Amulung" },
        { "name": "Aparri" },
        { "name": "Baggao" },
        { "name": "Ballesteros" },
        { "name": "Buguey" },
        { "name": "Calayan" },
        { "name": "Camalaniugan" },
        { "name": "Claveria" },
        { "name": "Enrile" },
        { "name": "Gattaran" },
        { "name": "Gonzaga" },
        { "name": "Iguig" },
        { "name": "Lal-lo" },
        { "name": "Lasam" },
        { "name": "Pamplona" },
        { "name": "Peñablanca" },
        { "name": "Piat" },
        { "name": "Rizal" },
        { "name": "Sanchez-Mira" },
        { "name": "Santa Ana" },
        { "name": "Santa Praxedes" },
        { "name": "Santa Teresita" },
        { "name": "Santo Niño" },
        { "name": "Solana" },
        { "name": "Tuao" }
      ]
    },
    {
      "name": "Camarines Norte",
      "cities": [
        { "name": "Daet", "isCapital": true },
        { "name": "Basud" },
        { "name": "Capalonga" },
        { "name": "Jose Panganiban" },
        { "name": "Labo" },
        { "name": "Mercedes" },
        { "name": "Paracale" },
        { "name": "San Lorenzo Ruiz" },
        { "name": "San Vicente" },
        { "name": "Santa Elena" },
        { "name": "Talisay" },
        { "name": "Vinzons" }
      ]
    },
    {
      "name": "Camarines Sur",
      "cities": [
        { "name": "Pili", "isCapital": true },
        { "name": "Naga City" },
        { "name": "Iriga City" },
        { "name": "Baao" },
        { "name": "Balatan" },
        { "name": "Bato" },
        { "name": "Bombon" },
        { "name": "Buhi" },
        { "name": "Bula" },
        { "name": "Cabusao" },
        { "name": "Calabanga" },
        { "name": "Camaligan" },
        { "name": "Canaman" },
        { "name": "Caramoan" },
        { "name": "Del Gallego" },
        { "name": "Gainza" },
        { "name": "Garchitorena" },
        { "name": "Goa" },
        { "name": "Lagonoy" },
        { "name": "Libmanan" },
        { "name": "Lupi" },
        { "name": "Magarao" },
        { "name": "Milaor" },
        { "name": "Minalabac" },
        { "name": "Nabua" },
        { "name": "Ocampo" },
        { "name": "Pamplona" },
        { "name": "Pasacao" },
        { "name": "Presentacion" },
        { "name": "Ragay" },
        { "name": "Sagñay" },
        { "name": "San Fernando" },
        { "name": "San Jose" },
        { "name": "Sipocot" },
        { "name": "Siruma" },
        { "name": "Tigaon" },
        { "name": "Tinambac" }
      ]
    },
    {
      "name": "Camiguin",
      "cities": [
        { "name": "Mambajao", "isCapital": true },
        { "name": "Catarman" },
        { "name": "Guinsiliban" },
        { "name": "Mahinog" },
        { "name": "Sagay" }
      ]
    },
    {
      "name": "Capiz",
      "cities": [
        { "name": "Roxas City", "isCapital": true },
        { "name": "Cuartero" },
        { "name": "Dao" },
        { "name": "Dumalag" },
        { "name": "Dumarao" },
        { "name": "Ivisan" },
        { "name": "Jamindan" },
        { "name": "Ma-ayon" },
        { "name": "Mambusao" },
        { "name": "Panay" },
        { "name": "Panitan" },
        { "name": "Pilar" },
        { "name": "Pontevedra" },
        { "name": "President Roxas" },
        { "name": "Sapi-an" },
        { "name": "Sigma" },
        { "name": "Tapaz" }
      ]
    },
    {
      "name": "Catanduanes",
      "cities": [
        { "name": "Virac", "isCapital": true },
        { "name": "Bagamanoc" },
        { "name": "Baras" },
        { "name": "Bato" },
        { "name": "Caramoran" },
        { "name": "Gigmoto" },
        { "name": "Pandan" },
        { "name": "Panganiban" },
        { "name": "San Andres" },
        { "name": "San Miguel" },
        { "name": "Viga" }
      ]
    },
    {
      "name": "Cavite",
      "cities": [
        { "name": "Trece Martires City", "isCapital": true },
        { "name": "Dasmariñas City" },
        { "name": "Bacoor City" },
        { "name": "Imus City" },
        { "name": "General Trias City" },
        { "name": "Cavite City" },
        { "name": "Tagaytay City" },
        { "name": "Alfonso" },
        { "name": "Amadeo" },
        { "name": "Carmona" },
        { "name": "General Emilio Aguinaldo" },
        { "name": "General Mariano Alvarez" },
        { "name": "Indang" },
        { "name": "Kawit" },
        { "name": "Magallanes" },
        { "name": "Maragondon" },
        { "name": "Mendez" },
        { "name": "Naic" },
        { "name": "Noveleta" },
        { "name": "Rosario" },
        { "name": "Silang" },
        { "name": "Tanza" },
        { "name": "Ternate" }
      ]
    },
    {
      "name": "Cebu",
      "cities": [
        { "name": "Cebu City", "isCapital": true },
        { "name": "Lapu-Lapu City" },
        { "name": "Mandaue City" },
        { "name": "Toledo City" },
        { "name": "Bogo City" },
        { "name": "Carcar City" },
        { "name": "Danao City" },
        { "name": "Naga City" },
        { "name": "Talisay City" },
        { "name": "Alcantara" },
        { "name": "Alcoy" },
        { "name": "Alegria" },
        { "name": "Aloguinsan" },
        { "name": "Argao" },
        { "name": "Asturias" },
        { "name": "Badian" },
        { "name": "Balamban" },
        { "name": "Bantayan" },
        { "name": "Barili" },
        { "name": "Boljoon" },
        { "name": "Borbon" },
        { "name": "Carmen" },
        { "name": "Catmon" },
        { "name": "Compostela" },
        { "name": "Consolacion" },
        { "name": "Cordoba" },
        { "name": "Daanbantayan" },
        { "name": "Dalaguete" },
        { "name": "Dumanjug" },
        { "name": "Ginatilan" },
        { "name": "Liloan" },
        { "name": "Madridejos" },
        { "name": "Malabuyoc" },
        { "name": "Medellin" },
        { "name": "Minglanilla" },
        { "name": "Moalboal" },
        { "name": "Oslob" },
        { "name": "Pilar" },
        { "name": "Pinamungahan" },
        { "name": "Poro" },
        { "name": "Ronda" },
        { "name": "Samboan" },
        { "name": "San Fernando" },
        { "name": "San Francisco" },
        { "name": "San Remigio" },
        { "name": "Santa Fe" },
        { "name": "Santander" },
        { "name": "Sibonga" },
        { "name": "Sogod" },
        { "name": "Tabogon" },
        { "name": "Tabuelan" },
        { "name": "Tuburan" }
      ]
    },
    {
      "name": "Cotabato",
      "cities": [
        { "name": "Kidapawan City", "isCapital": true },
        { "name": "Alamada" },
        { "name": "Aleosan" },
        { "name": "Antipas" },
        { "name": "Arakan" },
        { "name": "Banisilan" },
        { "name": "Carmen" },
        { "name": "Kabacan" },
        { "name": "Libungan" },
        { "name": "M'lang" },
        { "name": "Magpet" },
        { "name": "Makilala" },
        { "name": "Matalam" },
        { "name": "Midsayap" },
        { "name": "Pigcawayan" },
        { "name": "Pikit" },
        { "name": "President Roxas" },
        { "name": "Tulunan" }
      ]
    },
    {
      "name": "Davao de Oro",
      "cities": [
        { "name": "Nabunturan", "isCapital": true },
        { "name": "Compostela" },
        { "name": "Laak" },
        { "name": "Mabini" },
        { "name": "Maco" },
        { "name": "Maragusan" },
        { "name": "Mawab" },
        { "name": "Monkayo" },
        { "name": "Montevista" },
        { "name": "New Bataan" },
        { "name": "Pantukan" }
      ]
    },
    {
      "name": "Davao del Norte",
      "cities": [
        { "name": "Tagum City", "isCapital": true },
        { "name": "Island Garden City of Samal" },
        { "name": "Panabo City" },
        { "name": "Asuncion" },
        { "name": "Braulio E. Dujali" },
        { "name": "Carmen" },
        { "name": "Kapalong" },
        { "name": "New Corella" },
        { "name": "San Isidro" },
        { "name": "Santo Tomas" },
        { "name": "Talaingod" }
      ]
    },
    {
      "name": "Davao del Sur",
      "cities": [
        { "name": "Digos City", "isCapital": true },
        { "name": "Davao City" },
        { "name": "Bansalan" },
        { "name": "Don Marcelino" },
        { "name": "Hagonoy" },
        { "name": "Jose Abad Santos" },
        { "name": "Kiblawan" },
        { "name": "Magsaysay" },
        { "name": "Malalag" },
        { "name": "Malita" },
        { "name": "Matanao" },
        { "name": "Padada" },
        { "name": "Santa Cruz" },
        { "name": "Santa Maria" },
        { "name": "Sarangani" },
        { "name": "Sulop" }
      ]
    },
    {
      "name": "Davao Occidental",
      "cities": [
        { "name": "Malita", "isCapital": true },
        { "name": "Don Marcelino" },
        { "name": "Jose Abad Santos" },
        { "name": "Santa Maria" },
        { "name": "Sarangani" }
      ]
    },
    {
      "name": "Davao Oriental",
      "cities": [
        { "name": "Mati City", "isCapital": true },
        { "name": "Baganga" },
        { "name": "Banaybanay" },
        { "name": "Boston" },
        { "name": "Caraga" },
        { "name": "Cateel" },
        { "name": "Governor Generoso" },
        { "name": "Lupon" },
        { "name": "Manay" },
        { "name": "San Isidro" },
        { "name": "Tarragona" }
      ]
    },
    {
      "name": "Dinagat Islands",
      "cities": [
        { "name": "San Jose", "isCapital": true },
        { "name": "Basilisa" },
        { "name": "Cagdianao" },
        { "name": "Dinagat" },
        { "name": "Libjo" },
        { "name": "Loreto" },
        { "name": "Tubajon" }
      ]
    },
    {
      "name": "Eastern Samar",
      "cities": [
        { "name": "Borongan City", "isCapital": true },
        { "name": "Arteche" },
        { "name": "Balangiga" },
        { "name": "Balangkayan" },
        { "name": "Can-avid" },
        { "name": "Dolores" },
        { "name": "General MacArthur" },
        { "name": "Giporlos" },
        { "name": "Guiuan" },
        { "name": "Hernani" },
        { "name": "Jipapad" },
        { "name": "Lawaan" },
        { "name": "Llorente" },
        { "name": "Maslog" },
        { "name": "Maydolong" },
        { "name": "Mercedes" },
        { "name": "Oras" },
        { "name": "Quinapondan" },
        { "name": "Salcedo" },
        { "name": "San Julian" },
        { "name": "San Policarpo" },
        { "name": "Sulat" },
        { "name": "Taft" }
      ]
    },
    {
      "name": "Guimaras",
      "cities": [
        { "name": "Jordan", "isCapital": true },
        { "name": "Buenavista" },
        { "name": "Nueva Valencia" },
        { "name": "San Lorenzo" },
        { "name": "Sibunag" }
      ]
    },
    {
      "name": "Ifugao",
      "cities": [
        { "name": "Lagawe", "isCapital": true },
        { "name": "Aguinaldo" },
        { "name": "Alfonso Lista" },
        { "name": "Asipulo" },
        { "name": "Banaue" },
        { "name": "Hingyon" },
        { "name": "Hungduan" },
        { "name": "Kiangan" },
        { "name": "Lamut" },
        { "name": "Mayoyao" },
        { "name": "Tinoc" }
      ]
    },
    {
      "name": "Ilocos Norte",
      "cities": [
        { "name": "Laoag City", "isCapital": true },
        { "name": "Batac City" },
        { "name": "Adams" },
        { "name": "Bacarra" },
        { "name": "Badoc" },
        { "name": "Bangui" },
        { "name": "Banna" },
        { "name": "Burgos" },
        { "name": "Carasi" },
        { "name": "Currimao" },
        { "name": "Dingras" },
        { "name": "Dumalneg" },
        { "name": "Marcos" },
        { "name": "Nueva Era" },
        { "name": "Pagudpud" },
        { "name": "Paoay" },
        { "name": "Pasuquin" },
        { "name": "Piddig" },
        { "name": "Pinili" },
        { "name": "San Nicolas" },
        { "name": "Sarrat" },
        { "name": "Solsona" },
        { "name": "Vintar" }
      ]
    },
    {
      "name": "Ilocos Sur",
      "cities": [
        { "name": "Vigan City", "isCapital": true },
        { "name": "Candon City" },
        { "name": "Alilem" },
        { "name": "Banayoyo" },
        { "name": "Bantay" },
        { "name": "Burgos" },
        { "name": "Cabugao" },
        { "name": "Caoayan" },
        { "name": "Cervantes" },
        { "name": "Galimuyod" },
        { "name": "Gregorio del Pilar" },
        { "name": "Lidlidda" },
        { "name": "Magsingal" },
        { "name": "Nagbukel" },
        { "name": "Narvacan" },
        { "name": "Quirino" },
        { "name": "Salcedo" },
        { "name": "San Emilio" },
        { "name": "San Esteban" },
        { "name": "San Ildefonso" },
        { "name": "San Juan" },
        { "name": "San Vicente" },
        { "name": "Santa" },
        { "name": "Santa Catalina" },
        { "name": "Santa Cruz" },
        { "name": "Santa Lucia" },
        { "name": "Santa Maria" },
        { "name": "Santiago" },
        { "name": "Santo Domingo" },
        { "name": "Sigay" },
        { "name": "Sinait" },
        { "name": "Sugpon" },
        { "name": "Suyo" },
        { "name": "Tagudin" }
      ]
    },
    {
      "name": "Iloilo",
      "cities": [
        { "name": "Iloilo City", "isCapital": true },
        { "name": "Passi City" },
        { "name": "Ajuy" },
        { "name": "Alimodian" },
        { "name": "Anilao" },
        { "name": "Badiangan" },
        { "name": "Balasan" },
        { "name": "Banate" },
        { "name": "Barotac Nuevo" },
        { "name": "Barotac Viejo" },
        { "name": "Batad" },
        { "name": "Bingawan" },
        { "name": "Cabatuan" },
        { "name": "Calinog" },
        { "name": "Carles" },
        { "name": "Concepcion" },
        { "name": "Dingle" },
        { "name": "Dueñas" },
        { "name": "Dumangas" },
        { "name": "Estancia" },
        { "name": "Guimbal" },
        { "name": "Igbaras" },
        { "name": "Janiuay" },
        { "name": "Lambunao" },
        { "name": "Leganes" },
        { "name": "Lemery" },
        { "name": "Leon" },
        { "name": "Maasin" },
        { "name": "Miagao" },
        { "name": "Mina" },
        { "name": "New Lucena" },
        { "name": "Oton" },
        { "name": "Pavia" },
        { "name": "Pototan" },
        { "name": "San Dionisio" },
        { "name": "San Enrique" },
        { "name": "San Joaquin" },
        { "name": "San Miguel" },
        { "name": "San Rafael" },
        { "name": "Santa Barbara" },
        { "name": "Sara" },
        { "name": "Tigbauan" },
        { "name": "Tubungan" },
        { "name": "Zarraga" }
      ]
    },
    {
      "name": "Isabela",
      "cities": [
        { "name": "Ilagan City", "isCapital": true },
        { "name": "Cauayan City" },
        { "name": "Santiago City" },
        { "name": "Alicia" },
        { "name": "Angadanan" },
        { "name": "Aurora" },
        { "name": "Benito Soliven" },
        { "name": "Burgos" },
        { "name": "Cabagan" },
        { "name": "Cabatuan" },
        { "name": "Cordon" },
        { "name": "Delfin Albano" },
        { "name": "Dinapigue" },
        { "name": "Divilacan" },
        { "name": "Echague" },
        { "name": "Gamu" },
        { "name": "Jones" },
        { "name": "Luna" },
        { "name": "Maconacon" },
        { "name": "Mallig" },
        { "name": "Naguilian" },
        { "name": "Palanan" },
        { "name": "Quezon" },
        { "name": "Quirino" },
        { "name": "Ramon" },
        { "name": "Reina Mercedes" },
        { "name": "Roxas" },
        { "name": "San Agustin" },
        { "name": "San Guillermo" },
        { "name": "San Isidro" },
        { "name": "San Manuel" },
        { "name": "San Mariano" },
        { "name": "San Mateo" },
        { "name": "San Pablo" },
        { "name": "Santa Maria" },
        { "name": "Santo Tomas" },
        { "name": "Tumauini" }
      ]
    },
    {
      "name": "Kalinga",
      "cities": [
        { "name": "Tabuk City", "isCapital": true },
        { "name": "Balbalan" },
        { "name": "Lubuagan" },
        { "name": "Pasil" },
        { "name": "Pinukpuk" },
        { "name": "Rizal" },
        { "name": "Tanudan" },
        { "name": "Tinglayan" }
      ]
    },
    {
      "name": "La Union",
      "cities": [
        { "name": "San Fernando City", "isCapital": true },
        { "name": "Agoo" },
        { "name": "Aringay" },
        { "name": "Bacnotan" },
        { "name": "Bagulin" },
        { "name": "Balaoan" },
        { "name": "Bangar" },
        { "name": "Bauang" },
        { "name": "Burgos" },
        { "name": "Caba" },
        { "name": "Luna" },
        { "name": "Naguilian" },
        { "name": "Pugo" },
        { "name": "Rosario" },
        { "name": "San Gabriel" },
        { "name": "San Juan" },
        { "name": "Santo Tomas" },
        { "name": "Santol" },
        { "name": "Sudipen" },
        { "name": "Tubao" }
      ]
    },
    {
      "name": "Laguna",
      "cities": [
        { "name": "Santa Cruz", "isCapital": true },
        { "name": "Calamba City" },
        { "name": "San Pablo City" },
        { "name": "Biñan City" },
        { "name": "Cabuyao City" },
        { "name": "San Pedro City" },
        { "name": "Santa Rosa City" },
        { "name": "Alaminos" },
        { "name": "Bay" },
        { "name": "Calauan" },
        { "name": "Cavinti" },
        { "name": "Famy" },
        { "name": "Kalayaan" },
        { "name": "Liliw" },
        { "name": "Los Baños" },
        { "name": "Luisiana" },
        { "name": "Lumban" },
        { "name": "Mabitac" },
        { "name": "Magdalena" },
        { "name": "Majayjay" },
        { "name": "Nagcarlan" },
        { "name": "Paete" },
        { "name": "Pagsanjan" },
        { "name": "Pakil" },
        { "name": "Pangil" },
        { "name": "Pila" },
        { "name": "Rizal" },
        { "name": "Siniloan" },
        { "name": "Victoria" }
      ]
    },
    {
      "name": "Lanao del Norte",
      "cities": [
        { "name": "Tubod", "isCapital": true },
        { "name": "Iligan City" },
        { "name": "Bacolod" },
        { "name": "Baloi" },
        { "name": "Baroy" },
        { "name": "Kapatagan" },
        { "name": "Kauswagan" },
        { "name": "Kolambugan" },
        { "name": "Lala" },
        { "name": "Linamon" },
        { "name": "Magsaysay" },
        { "name": "Maigo" },
        { "name": "Matungao" },
        { "name": "Munai" },
        { "name": "Nunungan" },
        { "name": "Pantao Ragat" },
        { "name": "Pantar" },
        { "name": "Poona Piagapo" },
        { "name": "Salvador" },
        { "name": "Sapad" },
        { "name": "Sultan Naga Dimaporo" },
        { "name": "Tagoloan" },
        { "name": "Tangcal" },
        { "name": "Tubod" }
      ]
    },
    {
      "name": "Lanao del Sur",
      "cities": [
        { "name": "Marawi City", "isCapital": true },
        { "name": "Bacolod-Kalawi" },
        { "name": "Balabagan" },
        { "name": "Balindong" },
        { "name": "Bayang" },
        { "name": "Binidayan" },
        { "name": "Buadiposo-Buntong" },
        { "name": "Bubong" },
        { "name": "Butig" },
        { "name": "Calanogas" },
        { "name": "Ditsaan-Ramain" },
        { "name": "Ganassi" },
        { "name": "Kapai" },
        { "name": "Kapatagan" },
        { "name": "Lumba-Bayabao" },
        { "name": "Lumbaca-Unayan" },
        { "name": "Lumbatan" },
        { "name": "Lumbayanague" },
        { "name": "Madalum" },
        { "name": "Madamba" },
        { "name": "Maguing" },
        { "name": "Malabang" },
        { "name": "Marantao" },
        { "name": "Marogong" },
        { "name": "Masiu" },
        { "name": "Mulondo" },
        { "name": "Pagayawan" },
        { "name": "Piagapo" },
        { "name": "Poona Bayabao" },
        { "name": "Pualas" },
        { "name": "Saguiaran" },
        { "name": "Sultan Dumalondong" },
        { "name": "Picong" },
        { "name": "Tagoloan II" },
        { "name": "Tamparan" },
        { "name": "Taraka" },
        { "name": "Tubaran" },
        { "name": "Tugaya" },
        { "name": "Wao" }
      ]
    },
    {
      "name": "Leyte",
      "cities": [
        { "name": "Tacloban City", "isCapital": true },
        { "name": "Ormoc City" },
        { "name": "Baybay City" },
        { "name": "Abuyog" },
        { "name": "Alangalang" },
        { "name": "Albuera" },
        { "name": "Babatngon" },
        { "name": "Barugo" },
        { "name": "Bato" },
        { "name": "Burauen" },
        { "name": "Calubian" },
        { "name": "Capoocan" },
        { "name": "Carigara" },
        { "name": "Dagami" },
        { "name": "Dulag" },
        { "name": "Hilongos" },
        { "name": "Hindang" },
        { "name": "Inopacan" },
        { "name": "Isabel" },
        { "name": "Jaro" },
        { "name": "Javier" },
        { "name": "Julita" },
        { "name": "Kananga" },
        { "name": "La Paz" },
        { "name": "Leyte" },
        { "name": "MacArthur" },
        { "name": "Mahaplag" },
        { "name": "Matag-ob" },
        { "name": "Matalom" },
        { "name": "Mayorga" },
        { "name": "Merida" },
        { "name": "Palo" },
        { "name": "Palompon" },
        { "name": "Pastrana" },
        { "name": "San Isidro" },
        { "name": "San Miguel" },
        { "name": "Santa Fe" },
        { "name": "Tabango" },
        { "name": "Tabontabon" },
        { "name": "Tanauan" },
        { "name": "Tolosa" },
        { "name": "Tunga" },
        { "name": "Villaba" }
      ]
    },
    {
      "name": "Maguindanao del Norte",
      "cities": [
        { "name": "Datu Odin Sinsuat", "isCapital": true },
        { "name": "Barira" },
        { "name": "Buldon" },
        { "name": "Cotabato City" },
        { "name": "Datu Blah T. Sinsuat" },
        { "name": "Datu Odin Sinsuat" },
        { "name": "Kabuntalan" },
        { "name": "Matanog" },
        { "name": "Northern Kabuntalan" },
        { "name": "Parang" },
        { "name": "Sultan Kudarat" },
        { "name": "Sultan Mastura" },
        { "name": "Upi" }
      ]
    },
    {
      "name": "Maguindanao del Sur",
      "cities": [
        { "name": "Buluan", "isCapital": true },
        { "name": "Ampatuan" },
        { "name": "Barira" },
        { "name": "Buluan" },
        { "name": "Datu Abdullah Sangki" },
        { "name": "Datu Anggal Midtimbang" },
        { "name": "Datu Hoffer Ampatuan" },
        { "name": "Datu Montawal" },
        { "name": "Datu Paglas" },
        { "name": "Datu Piang" },
        { "name": "Datu Salibo" },
        { "name": "Datu Saudi-Ampatuan" },
        { "name": "Datu Unsay" },
        { "name": "General Salipada K. Pendatun" },
        { "name": "Guindulungan" },
        { "name": "Mamasapano" },
        { "name": "Mangudadatu" },
        { "name": "Pagalungan" },
        { "name": "Paglat" },
        { "name": "Pandag" },
        { "name": "Rajah Buayan" },
        { "name": "Shariff Aguak" },
        { "name": "Shariff Saydona Mustafa" },
        { "name": "South Upi" },
        { "name": "Sultan sa Barongis" },
        { "name": "Talayan" },
        { "name": "Talitay" }
      ]
    },
    {
      "name": "Marinduque",
      "cities": [
        { "name": "Boac", "isCapital": true },
        { "name": "Buenavista" },
        { "name": "Gasan" },
        { "name": "Mogpog" },
        { "name": "Santa Cruz" },
        { "name": "Torrijos" }
      ]
    },
    {
      "name": "Masbate",
      "cities": [
        { "name": "Masbate City", "isCapital": true },
        { "name": "Aroroy" },
        { "name": "Baleno" },
        { "name": "Balud" },
        { "name": "Batuan" },
        { "name": "Cataingan" },
        { "name": "Cawayan" },
        { "name": "Claveria" },
        { "name": "Dimasalang" },
        { "name": "Esperanza" },
        { "name": "Mandaon" },
        { "name": "Milagros" },
        { "name": "Mobo" },
        { "name": "Monreal" },
        { "name": "Palanas" },
        { "name": "Pio V. Corpuz" },
        { "name": "Placer" },
        { "name": "San Fernando" },
        { "name": "San Jacinto" },
        { "name": "San Pascual" },
        { "name": "Uson" }
      ]
    },
    {
      "name": "Misamis Occidental",
      "cities": [
        { "name": "Oroquieta City", "isCapital": true },
        { "name": "Ozamiz City" },
        { "name": "Tangub City" },
        { "name": "Aloran" },
        { "name": "Baliangao" },
        { "name": "Bonifacio" },
        { "name": "Calamba" },
        { "name": "Clarin" },
        { "name": "Concepcion" },
        { "name": "Don Victoriano Chiongbian" },
        { "name": "Jimenez" },
        { "name": "Lopez Jaena" },
        { "name": "Panaon" },
        { "name": "Plaridel" },
        { "name": "Sapang Dalaga" },
        { "name": "Sinacaban" },
        { "name": "Tudela" }
      ]
    },
    {
      "name": "Misamis Oriental",
      "cities": [
        { "name": "Cagayan de Oro City", "isCapital": true },
        { "name": "Gingoog City" },
        { "name": "Alubijid" },
        { "name": "Balingasag" },
        { "name": "Balingoan" },
        { "name": "Binuangan" },
        { "name": "Claveria" },
        { "name": "El Salvador City" },
        { "name": "Gitagum" },
        { "name": "Initao" },
        { "name": "Jasaan" },
        { "name": "Kinoguitan" },
        { "name": "Lagonglong" },
        { "name": "Laguindingan" },
        { "name": "Libertad" },
        { "name": "Lugait" },
        { "name": "Magsaysay" },
        { "name": "Manticao" },
        { "name": "Medina" },
        { "name": "Naawan" },
        { "name": "Opol" },
        { "name": "Salay" },
        { "name": "Sugbongcogon" },
        { "name": "Tagoloan" },
        { "name": "Talisayan" },
        { "name": "Villanueva" }
      ]
    },
    {
      "name": "Mountain Province",
      "cities": [
        { "name": "Bontoc", "isCapital": true },
        { "name": "Barlig" },
        { "name": "Bauko" },
        { "name": "Besao" },
        { "name": "Natonin" },
        { "name": "Paracelis" },
        { "name": "Sabangan" },
        { "name": "Sadanga" },
        { "name": "Sagada" },
        { "name": "Tadian" }
      ]
    },
    {
      "name": "Negros Occidental",
      "cities": [
        { "name": "Bacolod City", "isCapital": true },
        { "name": "Bago City" },
        { "name": "Cadiz City" },
        { "name": "Escalante City" },
        { "name": "Himamaylan City" },
        { "name": "Kabankalan City" },
        { "name": "La Carlota City" },
        { "name": "Sagay City" },
        { "name": "San Carlos City" },
        { "name": "Silay City" },
        { "name": "Sipalay City" },
        { "name": "Talisay City" },
        { "name": "Victorias City" },
        { "name": "Binalbagan" },
        { "name": "Calatrava" },
        { "name": "Candoni" },
        { "name": "Cauayan" },
        { "name": "Enrique B. Magalona" },
        { "name": "Hinigaran" },
        { "name": "Hino.ba-an" },
        { "name": "Ilog" },
        { "name": "Isabela" },
        { "name": "La Castellana" },
        { "name": "Manapla" },
        { "name": "Moises Padilla" },
        { "name": "Murcia" },
        { "name": "Pontevedra" },
        { "name": "Pulupandan" },
        { "name": "Salvador Benedicto" },
        { "name": "San Enrique" },
        { "name": "Toboso" },
        { "name": "Valladolid" }
      ]
    },
    {
      "name": "Negros Oriental",
      "cities": [
        { "name": "Dumaguete City", "isCapital": true },
        { "name": "Bais City" },
        { "name": "Bayawan City" },
        { "name": "Canlaon City" },
        { "name": "Guihulngan City" },
        { "name": "Tanjay City" },
        { "name": "Amlan" },
        { "name": "Ayungon" },
        { "name": "Bacong" },
        { "name": "Basay" },
        { "name": "Bindoy" },
        { "name": "Dauin" },
        { "name": "Jimalalud" },
        { "name": "La Libertad" },
        { "name": "Mabinay" },
        { "name": "Manjuyod" },
        { "name": "Pamplona" },
        { "name": "San Jose" },
        { "name": "Santa Catalina" },
        { "name": "Siaton" },
        { "name": "Sibulan" },
        { "name": "Tayasan" },
        { "name": "Valencia" },
        { "name": "Vallehermoso" },
        { "name": "Zamboanguita" }
      ]
    },
    {
      "name": "Northern Samar",
      "cities": [
        { "name": "Catarman", "isCapital": true },
        { "name": "Allen" },
        { "name": "Biri" },
        { "name": "Bobon" },
        { "name": "Capul" },
        { "name": "Catubig" },
        { "name": "Gamay" },
        { "name": "Laoang" },
        { "name": "Lapinig" },
        { "name": "Las Navas" },
        { "name": "Lavezares" },
        { "name": "Lope de Vega" },
        { "name": "Mapanas" },
        { "name": "Mondragon" },
        { "name": "Palapag" },
        { "name": "Pambujan" },
        { "name": "Rosario" },
        { "name": "San Antonio" },
        { "name": "San Isidro" },
        { "name": "San Jose" },
        { "name": "San Roque" },
        { "name": "San Vicente" },
        { "name": "Silvino Lobos" },
        { "name": "Victoria" }
      ]
    },
    {
      "name": "Nueva Ecija",
      "cities": [
        { "name": "Palayan City", "isCapital": true },
        { "name": "Cabanatuan City" },
        { "name": "Gapan City" },
        { "name": "San Jose City" },
        { "name": "Muñoz City" },
        { "name": "Aliaga" },
        { "name": "Bongabon" },
        { "name": "Cabiao" },
        { "name": "Carranglan" },
        { "name": "Cuyapo" },
        { "name": "Gabaldon" },
        { "name": "General Mamerto Natividad" },
        { "name": "General Tinio" },
        { "name": "Guimba" },
        { "name": "Jaen" },
        { "name": "Laur" },
        { "name": "Licab" },
        { "name": "Llanera" },
        { "name": "Lupao" },
        { "name": "Nampicuan" },
        { "name": "Pantabangan" },
        { "name": "Peñaranda" },
        { "name": "Quezon" },
        { "name": "Rizal" },
        { "name": "San Antonio" },
        { "name": "San Isidro" },
        { "name": "San Leonardo" },
        { "name": "Santa Rosa" },
        { "name": "Santo Domingo" },
        { "name": "Talavera" },
        { "name": "Talugtug" },
        { "name": "Zaragoza" }
      ]
    },
    {
      "name": "Nueva Vizcaya",
      "cities": [
        { "name": "Bayombong", "isCapital": true },
        { "name": "Solano" },
        { "name": "Alfonso Castaneda" },
        { "name": "Ambaguio" },
        { "name": "Aritao" },
        { "name": "Bagabag" },
        { "name": "Bambang" },
        { "name": "Diadi" },
        { "name": "Dupax del Norte" },
        { "name": "Dupax del Sur" },
        { "name": "Kasibu" },
        { "name": "Kayapa" },
        { "name": "Quezon" },
        { "name": "Santa Fe" },
        { "name": "Villaverde" }
      ]
    },
    {
      "name": "Occidental Mindoro",
      "cities": [
        { "name": "Mamburao", "isCapital": true },
        { "name": "Abra de Ilog" },
        { "name": "Calintaan" },
        { "name": "Looc" },
        { "name": "Lubang" },
        { "name": "Magsaysay" },
        { "name": "Paluan" },
        { "name": "Rizal" },
        { "name": "Sablayan" },
        { "name": "San Jose" },
        { "name": "Santa Cruz" }
      ]
    },
    {
      "name": "Oriental Mindoro",
      "cities": [
        { "name": "Calapan City", "isCapital": true },
        { "name": "Baco" },
        { "name": "Bansud" },
        { "name": "Bongabong" },
        { "name": "Bulalacao" },
        { "name": "Gloria" },
        { "name": "Mansalay" },
        { "name": "Naujan" },
        { "name": "Pinamalayan" },
        { "name": "Pola" },
        { "name": "Puerto Galera" },
        { "name": "Roxas" },
        { "name": "San Teodoro" },
        { "name": "Socorro" },
        { "name": "Victoria" }
      ]
    },
    {
      "name": "Palawan",
      "cities": [
        { "name": "Puerto Princesa City", "isCapital": true },
        { "name": "Aborlan" },
        { "name": "Agutaya" },
        { "name": "Araceli" },
        { "name": "Balabac" },
        { "name": "Bataraza" },
        { "name": "Brooke's Point" },
        { "name": "Busuanga" },
        { "name": "Cagayancillo" },
        { "name": "Coron" },
        { "name": "Culion" },
        { "name": "Cuyo" },
        { "name": "Dumaran" },
        { "name": "El Nido" },
        { "name": "Kalayaan" },
        { "name": "Linapacan" },
        { "name": "Magsaysay" },
        { "name": "Narra" },
        { "name": "Quezon" },
        { "name": "Rizal" },
        { "name": "Roxas" },
        { "name": "San Vicente" },
        { "name": "Sofronio Española" },
        { "name": "Taytay" }
      ]
    },
    {
      "name": "Pampanga",
      "cities": [
        { "name": "San Fernando City", "isCapital": true },
        { "name": "Angeles City" },
        { "name": "Mabalacat City" },
        { "name": "Apalit" },
        { "name": "Arayat" },
        { "name": "Bacolor" },
        { "name": "Candaba" },
        { "name": "Floridablanca" },
        { "name": "Guagua" },
        { "name": "Lubao" },
        { "name": "Macabebe" },
        { "name": "Magalang" },
        { "name": "Masantol" },
        { "name": "Mexico" },
        { "name": "Minalin" },
        { "name": "Porac" },
        { "name": "San Luis" },
        { "name": "San Simon" },
        { "name": "Santa Ana" },
        { "name": "Santa Rita" },
        { "name": "Santo Tomas" },
        { "name": "Sasmuan" }
      ]
    },
    {
      "name": "Pangasinan",
      "cities": [
        { "name": "Lingayen", "isCapital": true },
        { "name": "Dagupan City" },
        { "name": "San Carlos City" },
        { "name": "Alaminos City" },
        { "name": "Urdaneta City" },
        { "name": "Agno" },
        { "name": "Aguilar" },
        { "name": "Alcala" },
        { "name": "Anda" },
        { "name": "Asingan" },
        { "name": "Balungao" },
        { "name": "Bani" },
        { "name": "Basista" },
        { "name": "Bautista" },
        { "name": "Bayambang" },
        { "name": "Binalonan" },
        { "name": "Binmaley" },
        { "name": "Bolinao" },
        { "name": "Bugallon" },
        { "name": "Burgos" },
        { "name": "Calasiao" },
        { "name": "Dasol" },
        { "name": "Infanta" },
        { "name": "Labrador" },
        { "name": "Laoac" },
        { "name": "Mabini" },
        { "name": "Malasiqui" },
        { "name": "Manaoag" },
        { "name": "Mangaldan" },
        { "name": "Mangatarem" },
        { "name": "Mapandan" },
        { "name": "Natividad" },
        { "name": "Pozzorubio" },
        { "name": "Rosales" },
        { "name": "San Fabian" },
        { "name": "San Jacinto" },
        { "name": "San Manuel" },
        { "name": "San Nicolas" },
        { "name": "San Quintin" },
        { "name": "Santa Barbara" },
        { "name": "Santa Maria" },
        { "name": "Santo Tomas" },
        { "name": "Sison" },
        { "name": "Sual" },
        { "name": "Tayug" },
        { "name": "Umingan" },
        { "name": "Urbiztondo" },
        { "name": "Villasis" }
      ]
    },
    {
      "name": "Quezon",
      "cities": [
        { "name": "Lucena City", "isCapital": true },
        { "name": "Tayabas City" },
        { "name": "Agdangan" },
        { "name": "Alabat" },
        { "name": "Atimonan" },
        { "name": "Buenavista" },
        { "name": "Burdeos" },
        { "name": "Calauag" },
        { "name": "Candelaria" },
        { "name": "Catanauan" },
        { "name": "Dolores" },
        { "name": "General Luna" },
        { "name": "General Nakar" },
        { "name": "Guinayangan" },
        { "name": "Gumaca" },
        { "name": "Infanta" },
        { "name": "Jomalig" },
        { "name": "Lopez" },
        { "name": "Lucban" },
        { "name": "Macalelon" },
        { "name": "Mauban" },
        { "name": "Mulanay" },
        { "name": "Padre Burgos" },
        { "name": "Pagbilao" },
        { "name": "Panukulan" },
        { "name": "Patnanungan" },
        { "name": "Perez" },
        { "name": "Pitogo" },
        { "name": "Plaridel" },
        { "name": "Polillo" },
        { "name": "Quezon" },
        { "name": "Real" },
        { "name": "Sampaloc" },
        { "name": "San Andres" },
        { "name": "San Antonio" },
        { "name": "San Francisco" },
        { "name": "San Narciso" },
        { "name": "Sariaya" },
        { "name": "Tagkawayan" },
        { "name": "Tiaong" },
        { "name": "Unisan" }
      ]
    },
    {
      "name": "Quirino",
      "cities": [
        { "name": "Cabarroguis", "isCapital": true },
        { "name": "Aglipay" },
        { "name": "Diffun" },
        { "name": "Maddela" },
        { "name": "Nagtipunan" },
        { "name": "Saguday" }
      ]
    },
    {
      "name": "Rizal",
      "cities": [
        { "name": "Antipolo City", "isCapital": true },
        { "name": "Angono" },
        { "name": "Baras" },
        { "name": "Binangonan" },
        { "name": "Cainta" },
        { "name": "Cardona" },
        { "name": "Jalajala" },
        { "name": "Morong" },
        { "name": "Pililla" },
        { "name": "Rodriguez" },
        { "name": "San Mateo" },
        { "name": "Tanay" },
        { "name": "Taytay" },
        { "name": "Teresa" }
      ]
    },
    {
      "name": "Romblon",
      "cities": [
        { "name": "Romblon", "isCapital": true },
        { "name": "Alcantara" },
        { "name": "Banton" },
        { "name": "Cajidiocan" },
        { "name": "Calatrava" },
        { "name": "Concepcion" },
        { "name": "Corcuera" },
        { "name": "Ferrol" },
        { "name": "Looc" },
        { "name": "Magdiwang" },
        { "name": "Odiongan" },
        { "name": "San Agustin" },
        { "name": "San Andres" },
        { "name": "San Fernando" },
        { "name": "San Jose" },
        { "name": "Santa Fe" },
        { "name": "Santa Maria" }
      ]
    },
    {
      "name": "Samar",
      "cities": [
        { "name": "Catbalogan City", "isCapital": true },
        { "name": "Calbayog City" },
        { "name": "Almagro" },
        { "name": "Basey" },
        { "name": "Calbiga" },
        { "name": "Daram" },
        { "name": "Gandara" },
        { "name": "Hinabangan" },
        { "name": "Jiabong" },
        { "name": "Marabut" },
        { "name": "Matuguinao" },
        { "name": "Motiong" },
        { "name": "Pagsanghan" },
        { "name": "Paranas" },
        { "name": "Pinabacdao" },
        { "name": "San Jorge" },
        { "name": "San Jose de Buan" },
        { "name": "San Sebastian" },
        { "name": "Santa Margarita" },
        { "name": "Santa Rita" },
        { "name": "Santo Niño" },
        { "name": "Tagapul-an" },
        { "name": "Talalora" },
        { "name": "Tarangnan" },
        { "name": "Villareal" },
        { "name": "Zumarraga" }
      ]
    },
    {
      "name": "Sarangani",
      "cities": [
        { "name": "Alabel", "isCapital": true },
        { "name": "Glan" },
        { "name": "Kiamba" },
        { "name": "Maasim" },
        { "name": "Maitum" },
        { "name": "Malapatan" },
        { "name": "Malungon" }
      ]
    },
    {
      "name": "Siquijor",
      "cities": [
        { "name": "Siquijor", "isCapital": true },
        { "name": "Enrique Villanueva" },
        { "name": "Larena" },
        { "name": "Lazi" },
        { "name": "Maria" },
        { "name": "San Juan" }
      ]
    },
    {
      "name": "Sorsogon",
      "cities": [
        { "name": "Sorsogon City", "isCapital": true },
        { "name": "Barcelona" },
        { "name": "Bulan" },
        { "name": "Bulusan" },
        { "name": "Casiguran" },
        { "name": "Castilla" },
        { "name": "Donsol" },
        { "name": "Gubat" },
        { "name": "Irosin" },
        { "name": "Juban" },
        { "name": "Magallanes" },
        { "name": "Matnog" },
        { "name": "Pilar" },
        { "name": "Prieto Diaz" },
        { "name": "Santa Magdalena" }
      ]
    },
    {
      "name": "South Cotabato",
      "cities": [
        { "name": "Koronadal City", "isCapital": true },
        { "name": "General Santos City" },
        { "name": "Banga" },
        { "name": "Lake Sebu" },
        { "name": "Norala" },
        { "name": "Polomolok" },
        { "name": "Santo Niño" },
        { "name": "Surallah" },
        { "name": "T'boli" },
        { "name": "Tampakan" },
        { "name": "Tantangan" },
        { "name": "Tupi" }
      ]
    },
    {
      "name": "Southern Leyte",
      "cities": [
        { "name": "Maasin City", "isCapital": true },
        { "name": "Anahawan" },
        { "name": "Bontoc" },
        { "name": "Hinunangan" },
        { "name": "Hinundayan" },
        { "name": "Libagon" },
        { "name": "Liloan" },
        { "name": "Limasawa" },
        { "name": "Macrohon" },
        { "name": "Malitbog" },
        { "name": "Padre Burgos" },
        { "name": "Pintuyan" },
        { "name": "Saint Bernard" },
        { "name": "San Francisco" },
        { "name": "San Juan" },
        { "name": "San Ricardo" },
        { "name": "Silago" },
        { "name": "Sogod" },
        { "name": "Tomas Oppus" }
      ]
    },
    {
      "name": "Sultan Kudarat",
      "cities": [
        { "name": "Isulan", "isCapital": true },
        { "name": "Tacurong City" },
        { "name": "Bagumbayan" },
        { "name": "Columbio" },
        { "name": "Esperanza" },
        { "name": "Kalamansig" },
        { "name": "Lambayong" },
        { "name": "Lebak" },
        { "name": "Lutayan" },
        { "name": "Palimbang" },
        { "name": "President Quirino" },
        { "name": "Senator Ninoy Aquino" }
      ]
    },
    {
      "name": "Sulu",
      "cities": [
        { "name": "Jolo", "isCapital": true },
        { "name": "Banguingui" },
        { "name": "Hadji Panglima Tahil" },
        { "name": "Indanan" },
        { "name": "Kalingalan Caluang" },
        { "name": "Lugus" },
        { "name": "Luuk" },
        { "name": "Maimbung" },
        { "name": "Old Panamao" },
        { "name": "Omar" },
        { "name": "Pandami" },
        { "name": "Panglima Estino" },
        { "name": "Pangutaran" },
        { "name": "Parang" },
        { "name": "Pata" },
        { "name": "Patikul" },
        { "name": "Siasi" },
        { "name": "Talipao" },
        { "name": "Tapul" },
        { "name": "Tongkil" }
      ]
    },
    {
      "name": "Surigao del Norte",
      "cities": [
        { "name": "Surigao City", "isCapital": true },
        { "name": "Alegria" },
        { "name": "Bacuag" },
        { "name": "Burgos" },
        { "name": "Claver" },
        { "name": "Dapa" },
        { "name": "Del Carmen" },
        { "name": "General Luna" },
        { "name": "Gigaquit" },
        { "name": "Mainit" },
        { "name": "Malimono" },
        { "name": "Pilar" },
        { "name": "Placer" },
        { "name": "San Benito" },
        { "name": "San Francisco" },
        { "name": "San Isidro" },
        { "name": "Santa Monica" },
        { "name": "Sison" },
        { "name": "Socorro" },
        { "name": "Tagana-an" },
        { "name": "Tubod" }
      ]
    },
    {
      "name": "Surigao del Sur",
      "cities": [
        { "name": "Tandag City", "isCapital": true },
        { "name": "Bislig City" },
        { "name": "Barobo" },
        { "name": "Bayabas" },
        { "name": "Cagwait" },
        { "name": "Cantilan" },
        { "name": "Carmen" },
        { "name": "Carrascal" },
        { "name": "Cortes" },
        { "name": "Hinatuan" },
        { "name": "Lanuza" },
        { "name": "Lianga" },
        { "name": "Lingig" },
        { "name": "Madrid" },
        { "name": "Marihatag" },
        { "name": "San Agustin" },
        { "name": "San Miguel" },
        { "name": "Tagbina" },
        { "name": "Tago" }
      ]
    },
    {
      "name": "Tarlac",
      "cities": [
        { "name": "Tarlac City", "isCapital": true },
        { "name": "Anao" },
        { "name": "Bamban" },
        { "name": "Camiling" },
        { "name": "Capas" },
        { "name": "Concepcion" },
        { "name": "Gerona" },
        { "name": "La Paz" },
        { "name": "Mayantoc" },
        { "name": "Moncada" },
        { "name": "Paniqui" },
        { "name": "Pura" },
        { "name": "Ramos" },
        { "name": "San Clemente" },
        { "name": "San Jose" },
        { "name": "San Manuel" },
        { "name": "Santa Ignacia" },
        { "name": "Victoria" }
      ]
    },
    {
      "name": "Tawi-Tawi",
      "cities": [
        { "name": "Bongao", "isCapital": true },
        { "name": "Languyan" },
        { "name": "Mapun" },
        { "name": "Panglima Sugala" },
        { "name": "Sapa-Sapa" },
        { "name": "Sibutu" },
        { "name": "Simunul" },
        { "name": "Sitangkai" },
        { "name": "South Ubian" },
        { "name": "Tandubas" },
        { "name": "Turtle Islands" }
      ]
    },
    {
      "name": "Zambales",
      "cities": [
        { "name": "Iba", "isCapital": true },
        { "name": "Olongapo City" },
        { "name": "Botolan" },
        { "name": "Cabangan" },
        { "name": "Candelaria" },
        { "name": "Castillejos" },
        { "name": "Masinloc" },
        { "name": "Palauig" },
        { "name": "San Antonio" },
        { "name": "San Felipe" },
        { "name": "San Marcelino" },
        { "name": "San Narciso" },
        { "name": "Santa Cruz" },
        { "name": "Subic" }
      ]
    },
    {
      "name": "Zamboanga del Norte",
      "cities": [
        { "name": "Dipolog City", "isCapital": true },
        { "name": "Dapitan City" },
        { "name": "Bacungan" },
        { "name": "Baliguian" },
        { "name": "Godod" },
        { "name": "Gutalac" },
        { "name": "Jose Dalman" },
        { "name": "Kalawit" },
        { "name": "Katipunan" },
        { "name": "La Libertad" },
        { "name": "Labason" },
        { "name": "Liloy" },
        { "name": "Manukan" },
        { "name": "Mutia" },
        { "name": "Piñan" },
        { "name": "Polanco" },
        { "name": "President Manuel A. Roxas" },
        { "name": "Rizal" },
        { "name": "Salug" },
        { "name": "Sergio Osmeña Sr." },
        { "name": "Siayan" },
        { "name": "Sibuco" },
        { "name": "Sibutad" },
        { "name": "Sindangan" },
        { "name": "Siocon" },
        { "name": "Sirawai" },
        { "name": "Tampilisan" }
      ]
    },
    {
      "name": "Zamboanga del Sur",
      "cities": [
        { "name": "Pagadian City", "isCapital": true },
        { "name": "Zamboanga City" },
        { "name": "Aurora" },
        { "name": "Bayog" },
        { "name": "Dimataling" },
        { "name": "Dinas" },
        { "name": "Dumalinao" },
        { "name": "Dumingag" },
        { "name": "Guipos" },
        { "name": "Josefina" },
        { "name": "Kumalarang" },
        { "name": "Labangan" },
        { "name": "Lakewood" },
        { "name": "Lapuyan" },
        { "name": "Mahayag" },
        { "name": "Margosatubig" },
        { "name": "Midsalip" },
        { "name": "Molave" },
        { "name": "Pitogo" },
        { "name": "Ramon Magsaysay" },
        { "name": "San Miguel" },
        { "name": "San Pablo" },
        { "name": "Sominot" },
        { "name": "Tabina" },
        { "name": "Tambulig" },
        { "name": "Tigbao" },
        { "name": "Tukuran" },
        { "name": "Vincenzo A. Sagun" }
      ]
    },
    {
      "name": "Zamboanga Sibugay",
      "cities": [
        { "name": "Ipil", "isCapital": true },
        { "name": "Alicia" },
        { "name": "Buug" },
        { "name": "Diplahan" },
        { "name": "Imelda" },
        { "name": "Kabasalan" },
        { "name": "Mabuhay" },
        { "name": "Malangas" },
        { "name": "Naga" },
        { "name": "Olutanga" },
        { "name": "Payao" },
        { "name": "Roseller Lim" },
        { "name": "Siay" },
        { "name": "Talusan" },
        { "name": "Titay" },
        { "name": "Tungawan" }
      ]
    },
];